// Generated by https://quicktype.io

//interfaces para las respuestas del servidor de las noticias
export interface NewsResponse {
    status: string;
    totalResults: number;
    articles: Article[];
}

export interface Article {
    source: Source;
    author?: null | string;
    title: string;
    description?: string;
    url: string;
    urlToImage?: string;
    publishedAt: string;
    content?: null | string;
}

export interface Source {
    id?: string;
    name: string;
}

//interfaz para guardar las noticias por categorias

export interface ArticlesByCategoryAndPage {
    // Para indicar que el objeto va a tener varios elementos se indica con corchetes
    [key: string]: {
        page: number,
        articles: Article[] //son varios artículos
    }

}